# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MongoMigration < Formula
  desc "MongoDB migration tool with and MCP support"
  homepage "https://github.com/drewjocham/mongo-migration-tool"
  version "1.1.0-beta.3"
  license "MIT"

  depends_on "mongodb/brew/mongodb-community" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v1.1.0-beta.3/mongo-migration-tool_Darwin_x86_64.tar.gz"
      sha256 "7f752fa3181e620570b308a54f8a1278c0adf2ef4bd7282333f2e2b827a6cc6a"

      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v1.1.0-beta.3/mongo-migration-tool_Darwin_arm64.tar.gz"
      sha256 "ca19b9bb51357fdace6891200418a6bf6926df4413209e350defcfa5c66c9d4a"

      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v1.1.0-beta.3/mongo-migration-tool_Linux_x86_64.tar.gz"
      sha256 "de7c670c0d94f39459c020500698be7521a59d4e50d99512a4eff6b8bd23d494"
      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v1.1.0-beta.3/mongo-migration-tool_Linux_arm64.tar.gz"
      sha256 "e1621665119291e15ef2a9c9cec45083633ec00e6fc69879926634961263f7c7"
      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
  end

  test do
    system "#{bin}/mongo-migration --version"
  end
end
