# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MongoMigration < Formula
  desc "MongoDB migration tool with AI-powered insights and MCP support"
  homepage "https://github.com/drewjocham/mongo-migration-tool"
  version "0.1.0-beta.18"
  license "MIT"

  depends_on "mongodb/brew/mongodb-community" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.0-beta.18/mongo-migration-tool_Darwin_x86_64.tar.gz"
      sha256 "ad63bae2c8114711f77ea49bcff2decaf1f4e05d2e1871f41146f2912fbde76c"

      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.0-beta.18/mongo-migration-tool_Darwin_arm64.tar.gz"
      sha256 "2df2fb47b41ad6be25bdae97dd0b29101f9aa90d8ec848479716ba68c460a288"

      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.0-beta.18/mongo-migration-tool_Linux_x86_64.tar.gz"
      sha256 "8de7d281a19a5e7e25c1d4357b1b3dea96bee6021069794787644a8c46ac524d"
      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.0-beta.18/mongo-migration-tool_Linux_arm64.tar.gz"
      sha256 "7d8a8ececa6ff34d84d8bd1b9d46f69c115b4bcbce6aa944378281e70ceff355"
      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
  end

  test do
    system "#{bin}/mongo-migration --version"
  end
end
