# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MongoMigration < Formula
  desc "MongoDB migration tool with AI-powered insights and MCP support"
  homepage "https://github.com/drewjocham/mongo-migration-tool"
  version "0.1.0-beta.19"
  license "MIT"

  depends_on "mongodb/brew/mongodb-community" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.0-beta.19/mongo-migration-tool_Darwin_x86_64.tar.gz"
      sha256 "635055d96ed04c199be09eecc134b31c68cd9377b21c86e2c2c6d1280bcf39b6"

      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.0-beta.19/mongo-migration-tool_Darwin_arm64.tar.gz"
      sha256 "fa9fbe76fe3308dc678738f4fc2ed2374f9489a691ffd27727e500034dbb1837"

      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.0-beta.19/mongo-migration-tool_Linux_x86_64.tar.gz"
      sha256 "5a3a87aff0c0e2cfc935369d9e1145b6c950f1657514d8bf33db2792d6ca18dd"
      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.0-beta.19/mongo-migration-tool_Linux_arm64.tar.gz"
      sha256 "283a4518599e506965dbdae51e2adca4a0fb4c280fa36f0dcfeb84b6a9032742"
      def install
        bin.install "mongo-migration"

        # Install example configurations
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "MCP.md"
      end
    end
  end

  test do
    system "#{bin}/mongo-migration --version"
  end
end
