# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MongoTool < Formula
  desc "MongoDB migration tool with MCP support"
  homepage "https://github.com/drewjocham/mongo-migration-tool"
  version "0.1.2-beta.7"
  license "MIT"

  depends_on "mongodb/brew/mongodb-community" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.2-beta.7/mongo-migration-tool_Darwin_x86_64.tar.gz"
      sha256 "354cd8cbe0b3c6de72256f03e8e569359a0b0c882075ca608df8c57efffbdb27"

      def install
        bin.install "mongo-tool"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.2-beta.7/mongo-migration-tool_Darwin_arm64.tar.gz"
      sha256 "0ad17ecb724ac0ffab3de96bfba827d5ab1b2f24be04b29577f704a307502b27"

      def install
        bin.install "mongo-tool"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.2-beta.7/mongo-migration-tool_Linux_x86_64.tar.gz"
      sha256 "8e17481405a709cf15a514cf4fddeba4047b0d8b39a71ce776538ea2379bb961"
      def install
        bin.install "mongo-tool"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/drewjocham/mongo-migration-tool/releases/download/v0.1.2-beta.7/mongo-migration-tool_Linux_arm64.tar.gz"
      sha256 "c1f61912e730a72655eb4fe67b02aab9b8ff2d4c0439975a04dd5ef79a13ddcf"
      def install
        bin.install "mongo-tool"
        pkgshare.install ".env.example"
        pkgshare.install "examples"
        pkgshare.install "mcp.md"
      end
    end
  end

  test do
    system "#{bin}/mongo-tool --version"
  end
end
